sudo: required
services: 
  - docker


before_install: 
  - docker build -t midhunsudhakar/docker-react-app -f  Dockerfile.dev .

script:
  docker run midhunsudhakar/docker-react-app npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-west-2-722200435155"
  bucket_path: "docker-react-app"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$SECRET_ACCESS_KEY" 

    
