sudo: required
services: 
  - docker


before_install: 
  - docker build -t midhunsudhakar/docker-react-app -f  Dockerfile.dev .

script:
  docker run midhunsudhakar/docker-react-app npm run test -- --coverage
